apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: b-system-trigger
  namespace: b-system-cicd-demo
spec:
  params:
    - description: The git repository url
      name: git-repo-url
    - default: main
      description: The git revision
      name: git-revision
    - description: The name of the deployment to be created / patched
      name: git-repo-name
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName:  b-system-pipeline-app-
        namespace: b-system-cicd-demo
      spec:
        params:
          - name: GIT_REPO
            value: $(tt.params.git-repo-url)
          - name: GIT_REVISION
            value: $(tt.params.git-revision)
          - name: IMAGE_NAME
            value: 'jp.icr.io/cti-roks-training/b-system-app:latest' #cr path
        pipelineRef:
          name: b-system-pipeline-app #pipeline name
        serviceAccountName: pipeline
        workspaces:
          - name: workspace
            persistentVolumeClaim:
              claimName: sample-pvc-1
