apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: b-system-trigger-app
spec:
  serviceAccountName: pipeline
  interceptors:
    - ref:
        name: "github"
      params:
        - name: "secretRef"
          value:
            secretName: b-system-github-secret-app
            secretKey: secretToken
        - name: "eventTypes"
          value: ["push"]
  bindings:
    - ref: b-system-trigger
  template:
    ref: b-system-trigger
