kind: Deployment
apiVersion: apps/v1
metadata:
  name: b-system-app #deployment name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: b-system-app
  template:
    metadata:
      labels:
        app: b-system-app
    spec:
      containers:
        - name: b-system-app #container name
          image: jp.icr.io/cti-roks-training/b-system-app:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8083
              protocol: TCP
      imagePullSecrets:
        - name: all-icr-io
---
kind: Service
apiVersion: v1
metadata:
  name: b-system-app #service name
spec:
  ports:
    - name: http-8083 #port name
      port: 8083
      protocol: TCP
      targetPort: 8083
  selector:
    app: b-system-app #deployment label
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: b-system-app #route name
spec:
  to:
    kind: Service
    name: b-system-app #service name
  tls:
    termination: edge
  port:
    targetPort: http-8083 #port name
